# This is a basic workflow to help you get started with Actions
name: blank

on:
  discussion:
    types: [created, edited, answered]

jobs:
  debugging:    
    name: Dump event payload
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
