name: galaxy-brain-request

on:
  discussion:
    types: [labeled]

jobs:
  make-questions:
    if: >
      github.event.discussion.category.slug == 'galaxy-brain-request' 
      && github.event.discussion.state == 'open' 
      && github.event.label.name == 'help wanted'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/discussion
        id: request
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
