name: galaxy-brain

on:
  discussion_comment:
    types: [created]

jobs:
  mark-as-answers:
    if: github.event.discussion.category.slug == "galaxy-brain"
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - uses: ./.github/actions/discussion
